MVP and button functionality implemented
ezequielsetzesglobant/ParkingSystem pull request #2
Opened 2021-06-11 18:59 UTC by ezequielsetzesglobant

The button was given functionality, where the button is pressed and a fixed number is set. 
The MVP was implemented. 
And the contracts were implemented.

Package structure
![image](https://user-images.githubusercontent.com/84338513/121738515-b1cde080-cad0-11eb-8ce9-d29e6a842c69.png)

Image of the application running
![image](https://user-images.githubusercontent.com/84338513/121740330-518c6e00-cad3-11eb-9d7a-f770f09f01b0.png)

2021-06-11 19:01 UTC, mauroLonghi commented on app/build.gradle
> +
Pls remove empty spaces

2021-06-11 19:40 UTC, SartiMau commented on app/build.gradle
> +
leave only one here ;)

2021-06-11 19:43 UTC, SartiMau requested changes

2021-06-11 19:43 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/model/ParkingModel.java
> +
remove this extra line pls

2021-06-11 19:43 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ParkingPresenter.java
> +    private ParkingModel model;
you should use here the contract types

2021-06-11 19:43 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ParkingPresenter.java
> +    public ParkingPresenter(ParkingModel model, ParkingView view) {
same here

2021-06-11 19:43 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ParkingPresenter.java
> +
remove this extra line pls

2021-06-11 19:43 UTC, SartiMau commented on app/src/main/java/com/example/parkingsystem/mvp/view/ParkingView.java
> +
remove this extra line pls

2021-06-11 20:18 UTC, lucianoeli approved these changes

2021-06-11 20:53 UTC, ezequielsetzesglobant commented on app/src/main/java/com/example/parkingsystem/mvp/view/ParkingView.java
> +
Done

2021-06-11 20:53 UTC, ezequielsetzesglobant commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ParkingPresenter.java
> +
Done

2021-06-11 20:53 UTC, ezequielsetzesglobant commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ParkingPresenter.java
> +    public ParkingPresenter(ParkingModel model, ParkingView view) {
Done

2021-06-11 20:54 UTC, ezequielsetzesglobant commented on app/src/main/java/com/example/parkingsystem/mvp/presenter/ParkingPresenter.java
> +    private ParkingModel model;
Done

2021-06-11 20:55 UTC, ezequielsetzesglobant commented on app/src/main/java/com/example/parkingsystem/mvp/model/ParkingModel.java
> +
Done

2021-06-11 20:55 UTC, ezequielsetzesglobant commented on app/build.gradle
> +
Done

2021-06-11 21:01 UTC, SartiMau approved these changes

2021-06-14 12:28 UTC, mauroLonghi approved these changes

2021-06-14 12:31 UTC, BQuinteros approved these changes

2021-06-14 16:34 UTC, merged